#!/bin/sh
rm -rf /var/cache/* /tmp/*
mkdir -p /var/cache/apk/
find "$1" \( -name ".gitignore" -o -name ".git" \) -prune -exec rm -rf "{}" \;
find "$1" \( -name ".gitattributes" -o -name "*example*" \) -prune -exec rm -rf "{}" \;
find "$1" \( -name "test" -o -name "tests" \) -prune -exec rm -rf "{}" \;
find "$1" \( -name "*.jpg" -o -name "*.jpeg" \) -exec rm -f "{}" \;
find "$1" \( -name "*.h" -o -name "*.cpp" \) -exec rm -f "{}" \;
find "$1" \( -name "*.c" -o -name "*README*" \) -exec rm -f "{}" \;
find "$1" \( -name "*example*" -o -name "*.sample" \) -exec rm -f "{}" \;
find "$1" \( -name "*.png" -o -name "*.gif" \) -exec rm -f "{}" \;
find "$1" \( -name "*tutorial*" -o -name "Makefile" \) -exec rm -f "{}" \;
find "$1"  -name "*.ico" -exec rm -f "{}" \;
