#!/bin/sh
rm -rf /var/cache/* /tmp/*
mkdir -p /var/cache/apk/
find "$1" \( -name "doc" -o -name "docs" \) -prune -exec rm -rf "{}" \;
find "$1" \( -name ".gitignore" -o -name ".git" \) -prune -exec rm -rf "{}" \;
find "$1" \( -name ".gitattributes" -o -name "*example*" \) -prune -exec rm -rf "{}" \;
find "$1" \( -name "test" -o -name "tests" \) -prune -exec rm -rf "{}" \;

find "$1" \( -name "*.txt" -o -name "*.ico" \) -exec rm -f "{}" \;
find "$1" \( -name "*.jpg" -o -name "*.jpeg" \) -exec rm -f "{}" \;
find "$1" \( -name "*.h" -o -name "*.cpp" \) -exec rm -f "{}" \;
find "$1" \( -name "*.c" -o -name "*README*" \) -exec rm -f "{}" \;
find "$1" \( -name "*example*" -o -name "*.sample" \) -exec rm -f "{}" \;
find "$1" \( -name "*.png" -o -name "*.gif" \) -exec rm -f "{}" \;
find "$1" \( -name "*.sh" -o -name "Makefile" \) -exec rm -f "{}" \;

#fix for the Vim plugins help tags generation
mkdir -p /usr/share/vim/vim74/doc/
echo " " > /usr/share/vim/vim74/doc/help.txt    
